repository:
    url: https://bitbucket.org/charmpitz/configs/src
    branch: master
    ssh_key: /home/ady/configs/deployment_key

machines:
    -
        hostname: tes-dev.local
        username: vagrant
        password: vagrant
        ssh_key: /home/ady/workspace/vtes/puphpet/files/dot/ssh/id_rsa
        path: /home/vagrant/configs
    -
        hostname: dev.workers.etsgbv-work.com
        username: ubuntu
        password: ubuntu
        ssh_key:
        path: /home/ubuntu/configs
    -
        hostname: dev.emo.etsgbv-work.com
        username: ubuntu
        password: ubuntu
        ssh_key:
        path: /home/ubuntu/configs

